---
title: "crypto tracker"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    css: www/styles.css
    logo: www/favicon.ico
    favicon: www/favicon.ico
    social: [ "twitter", "linkedin", "menu"]
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(googlesheets)
library(RCrypto)
library(tidyverse)
library(dygraphs)
library(xts)

# to setup googlesheet auth (comment out once done) -----------------------------------
#shiny_token <- gs_auth() # authenticate w/ your desired Google identity here
#saveRDS(shiny_token, "shiny_app_token.rds")

new_prices <- RCrypto::CoinMarketCap_Ticker("GBP", c("BTC", "ETH")) %>% 
  mutate(last_updated = as.POSIXct(as.numeric(last_updated), origin = "1970-01-01")) %>%
  mutate_at(vars(contains("price")), as.numeric) %>% 
  select(name, date = last_updated, price_usd, price_gbp)

googlesheets::gs_auth(token = "shiny_app_token.rds")
sheet_key <- "1T77AEDJxLtb7_sr4nrfyYR9Xkj6w0mMDFKhsMSK-Ykc"

gs_key(sheet_key) %>%
  gs_add_row(input = new_prices)

coinz_raw <- googlesheets::gs_key(sheet_key) %>%
  gs_read_csv() %>%
  bind_rows(new_prices) %>% 
  arrange(name, date) %>% 
  distinct()

rm(new_prices)

```

Inputs {.sidebar}
-----------------------------------------------------------------------
Welcome to the [Culture of Insight's](https://cultureofinsight.com/) crypto tracking tool.

The tracker fetches real-time prices from the [coinmarketcap API](https://coinmarketcap.com/api/) every time it is launched then writes them to a googlesheets database.

For personalised metrics, enter the amount of the selected coin you own and when you acquired it below:

---

```{r}
selectInput("coin", "What Crypto?", c("Bitcoin", "Ethereum"))

numericInput("n", "How many coins?", 1, min = 0, max = 100, step = 0.01)

dateInput("date", "Date Purchased:", value = "2018-01-01 00:00:00", min = NULL, max = Sys.time(),
  format = "d MM yyyy", startview = "month", weekstart = 0,
  language = "en", width = NULL)

radioButtons('currency', 'Currency', c('GBP', 'USD'), inline = TRUE)
```

---

Use the range slider at the bottom of the chart to see historical prices.

This dashboard was built using:

- [R](https://www.r-project.org/)
- [shiny](http://rmarkdown.rstudio.com/flexdashboard/shiny.html)
- [googlesheets](https://github.com/jennybc/googlesheets)
- [RCrypto](https://cran.r-project.org/web/packages/RCrypto/index.html)
- [dygraphs](https://rstudio.github.io/dygraphs/)

Contact [paul@cultureofinsight.com](mailto:paul@cultureofinsight.com) with any enquires.

Row
-----------------------------------------------------------------------

### Current Value

```{r}
valueBoxOutput("value")
```

### ROI

```{r}
valueBoxOutput("roi")
```

### ROI %

```{r}
valueBoxOutput("roi_pct")
```

Row 
-----------------------------------------------------------------------

###

```{r}
dygraphOutput("chart")
```

```{r, server}

  coinz <- reactive({
    coinz_raw %>% 
      filter(name == input$coin) %>% 
      select(-name) %>% 
      mutate(USD = input$n * price_usd, 
             GBP = input$n * price_gbp)
  })
  
  stock <- reactive({
    coinz() %>% 
      filter(date >= input$date) %>% 
      mutate(daily_pct = (price_usd - lag(price_usd)) / lag(price_usd)) %>% 
      mutate(total_pct = (price_usd - price_usd[1]) / price_usd[1])
  })
  
  column_select <- reactive({
    switch(input$currency,
           GBP = 5,
           USD = 4)
  })
  
  output$value <- renderValueBox({
    value <- dplyr::last(stock()[[column_select()]])
    render_value <- paste0(ifelse(column_select() == 5, "£", "$"), round(value, digits = 0))
    valueBox(render_value, 
             paste("Current Value Last Updated @ ", format(max(stock()$date), format = "%H:%M")), 
             icon = ifelse(column_select() == 5, "fa-gbp", "fa-usd"), color = "SteelBlue")
  })
  
  output$roi <- renderValueBox({
    gainz <- dplyr::last(stock()[[column_select()]]) - dplyr::first(stock()[[column_select()]])
    render_value <- paste0(ifelse(column_select() == 5, "£", "$"), round(gainz, digits = 0))
    valueBox(render_value, "ROI", icon = "fa-line-chart", color = "DarkCyan")
  })
  
  output$roi_pct <-renderValueBox({
    pct <- dplyr::last(stock()$total_pct)
    render_value <- paste0(round(pct, digits = 3) * 100, "%")
    valueBox(render_value, "ROI %", icon = "fa-percent", color = "LightCoral")
  })
  
  output$chart <- renderDygraph({
    
    coinz_ts <- xts(coinz()[,column_select()], coinz()$date)
      
    dygraph(coinz_ts, main = paste(input$n, input$coin, input$currency, "Value")) %>% 
      #dySeries("V1", label = input$currency) %>%
      dyEvent(input$date, "Date of Purchase", labelLoc = "bottom") %>% 
      dyRangeSelector(dateWindow = c(as.character(input$date - 7), as.character(Sys.time()))) %>% 
      dyLimit(as.numeric(coinz_ts[as.character(input$date)]), color = "red") %>% 
      dyOptions(fillGraph = TRUE, gridLineWidth = .1)
    
  })

```

